### ISSUE TITLE
Enable posibility to only map certain properties of the json object instead of all

### ISSUE THREAD

**Issue by dstollie** [CupCoffee/Reify#1] opened 2016-11-16 22:52 UTC
Currently it is not possible to map only a certain set of properties. If I try to do this im getting "unresolved property" errors

**Comment by CupCoffee** [comment] 2016-11-20 14:16
This error is thrown when the class given in the **@var** statement couldn't be resolved. This indicates that the class Maps are faulty and should be fixed.

**Comment by dstollie** [comment] 2016-12-21 00:41
Im currently in a situation where that is not the case; 

Only mapping the following array

```
array:22 [▼
  "title" => "Transactional form"
  "description" => ""
  "labelPlacement" => "top_label"
  "descriptionPlacement" => "below"
  "button" => array:3 [▶]
  "fields" => array:4 [▶]
  "version" => "2.1.1"
  "id" => 1
  "useCurrentUserAsAuthor" => true
  "postContentTemplateEnabled" => false
  "postTitleTemplateEnabled" => false
  "postTitleTemplate" => ""
  "postContentTemplate" => ""
  "lastPageButton" => null
  "pagination" => null
  "firstPageCssClass" => null
  "simpleaddon" => array:1 [▶]
  "notifications" => array:1 [▶]
  "confirmations" => array:1 [▶]
  "is_active" => "1"
  "date_created" => "2016-12-17 12:58:56"
  "i
```

To the following class
```php
class Form {

	/**
	 * @var integer
	 */
	public $id;
}
```

With the following code
```php
return ( new Mapper() )->map( new ArrayMapper(), $settings )->to( FormSettings::class );
```

Gives me the following error:

```
Fatal error: Uncaught ReflectionException: Class GFConversationalFormAddOn\Objects\Form does not exist in /home/vagrant/Sites/bedrock/web/app/plugins/gravityforms-conversational-form-addon/vendor/cupcoffee/mapper/src/Map/MapObject.php on line 28
```

**Comment by CupCoffee** [comment] 2017-01-09 20:40
I'm closing this issue since there is no way for me to reproduce this.

**Closed by CupCoffee** 2017-01-09 20:40 UTC
